tuandai:
  globals:
    peWebsiteHost: 'http://www.paisheng.com'
    peWapHost: 'http://10.100.11.195:9333/wap/'
    serviceTelno: '0769-26987956'
    androidDownloadUrl: 'http://image.tuandai.com/tuandaiapp/tuandai.apk'
    iphoneDownloadUrl: 'http://image.tuandai.com/tuandaiapp/tuandai.apk'
  filter:
        refererUrls: "/user/resetSubmit,/user/forgetPwd,/user/resetPage,/account/toResetPwd,/account/toResetPwdResult"
        extRefererUrls: "/account/getauthInfo,/account/riskAssessment"
tuandaipe:
  config:
    wap-static-site: "https://m.paisheng.com"
    for-the-record: " 蜀ICP备16023674号"

app:
  web:
    project: true


