tuandai:
  globals:
    peWebsiteHost: 'www.paisheng.com'
    peWapHost: 'm.paisheng.com'
    serviceTelno: '0769-26987956'
  filter:
      refererUrls: "/user/resetSubmit,/user/forgetPwd,/user/resetPage,/account/toResetPwd,/account/toResetPwdResult,/user/getauthInfo"
      extRefererUrls: "/user/getauthInfo,/account/riskAssessment"
tuandaipe:
  config:
    wap-static-site: "http://localhost:9333/wap"
    for-the-record: " 蜀ICP备16023674号"

app:
  web:
    project: true
