tuandai:
  globals:
    peWebsiteHost: 'http://localhost:9333'
    peWapHost: 'http://localhost:9333/wap'
    serviceTelno: '0769-26987956'
    androidDownloadUrl: 'http://image.tuandai.com/tuandaiapp/tuandai.apk'
    iphoneDownloadUrl: 'http://image.tuandai.com/tuandaiapp/tuandai.apk'
  filter:
      refererUrls: "/user/resetSubmit,/user/forgetPwd,/user/resetPage,/account/toResetPwd,/account/toResetPwdResult,/account/getauthInfo"
      extRefererUrls: "/account/getauthInfo,/account/riskAssessment"
tuandaipe:
  config:
    wap-static-site: "http://localhost:9333/wap"
    for-the-record: " 蜀ICP备16023674号"

app:
  web:
    project: true


