# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml
#    configuration:
#      map-underscore-to-camelCase: true

# Discovery Server Access
eureka:
  instance:
    # hostname: localhost
    preferIpAddress: true

  client:
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
    initialInstanceInfoReplicationIntervalSeconds: 20
    registerWithEureka: true
    fetchRegistry: true

hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
  threadpool.default.coreSize: 10

feign:
  hystrix:
    enabled: false
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
