#########################【团贷API】##################################
tuandai-api:
  user-host: http://10.100.11.110:9207
  user-token: A2F609DF1W3S06QRW2E
  user-getUserInfo-token: PB3FS63W23LTD09P8I9
  user-register: /NiwoPassport/PostRegisterUser
  user-login: /NiwoPassport/PostUserLogin
  user-modifyPassword: /Common/PostUpdatePwdByUserId
  user-getUserInfoByUid: /SiMuFund/PostUserInfos
  user-getUidByMobile: /NiwoPassport/PostGetUserIdByMobile
  user-realNameAuth: /Common/PostUpdateIdentity
  msg-host: http://10.100.11.110:9201
  msg-emailOrSms: /Message.svc
  msg-voiceSms: /PublicService.svc
  msg-test-code: "123456"
  defaultUserHeadimage: "https://ss1.baidu.com/6ONXsjip0QIZ8tyhnq/it/u=660949300,1106686544&fm=58&u_exp_0=93915685,773381134&fm_exp_0=86&bpow=647&bpoh=740"
  serviceTelNo: "0769-23601234"

#########################【redis】##################################
tuandai:
  redis:
    pe:
      database: 8
      password: admin
      sentinel:
        master: mymaster
        nodes: '10.100.11.211:26379,10.100.11.11:26379,10.100.11.17:26379'
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0



#########################【短信模板】##################################
template:
  sms: "验证码：{ValidateCode}，请勿泄露于他人，如非本人操作，建议及时修改账号和密码。微信关注“派生财富”公众号可获取更多贴心服务哦。"

